### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ocefpaf** [callumrollo/cmcrameri#19]
Let's stay ahead of the curve and release a new version with the matplotlib deprecation fix from #15 ?

Let me know if I can help with that.

**Comment by callumrollo** [comment]
Sure, the pypi workflow you've made should push to pypi on any merged PR or release if I'm reading it correctly. I just need to setup a pypI token in github secrets, right?

**Comment by callumrollo** [comment]
PYPI_API_TOKEN is already in place from when I tried to automate this before. Shall I make a release and see if that successfully runs the workflow?

**Comment by ocefpaf** [comment]
Yep. Creating a release on GH should do the trick. You can even use the GH autogenerated changelog to make ti easier.

**Comment by callumrollo** [comment]
Cool. I'm just about to leave work, I'll take a punt at this tomorrow morning. Is this the changelog generator? https://github.com/github-changelog-generator/github-changelog-generator

**Comment by callumrollo** [comment]
Getting  a 404 on upload to PyPI

https://github.com/callumrollo/cmcrameri/actions/runs/4434846224/jobs/7781263975

Strangely it tried to upload to https://pypi.org/legacy/       

Looks like we've hit this issue from the pypi-publish action

https://github.com/pypa/gh-action-pypi-publish/issues/130

**Comment by callumrollo** [comment]
We can wait for it to be fixed in pypi-publish or try specifying the url in the action yml:
```
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
```

**Comment by callumrollo** [comment]
pypi-actions has been fixed. I pushed a commit to the readme to trigger the GH action, but it didn't upload to PyPI. Maybe because there hasn't been a new tag/release? https://github.com/callumrollo/cmcrameri/actions/runs/4435381491/jobs/7782462165

What's the best practice in a case like this? Upload to PyPI manually? Make a new tagged release to hopefully trigger the action to run fully?

**Comment by webknjaz** [comment]
> We can wait for it to be fixed

FYI I've fixed this upstream. Also, another workaround is sometimes using a previous version — they are all tagged in the action repo.

**Comment by ocefpaf** [comment]
> What's the best practice in a case like this? Upload to PyPI manually? Make a new tagged release to hopefully trigger the action to run fully?

Manual upload for now is fine. We have dependabot here that will update the GHA soon.
