### ISSUE TITLE
Update the colormaps to Scientific colour maps version 8.0

### ISSUE THREAD

**Issue by zak489** [callumrollo/cmcrameri#23]
Hi there, 

Nice work on integrating the Scientific colour maps into python (and pip). Could you also update the version of the code in pip from colour maps version 7 to version 8?

Thanks,
Zak

**Comment by callumrollo** [comment]
Thanks for the ping! I didn't realise Fabio had released a new version. I'm off on vacation at the moment, I'll add the latest version when I get back in a couple weeks. Or you're welcome to do a PR :)

**Comment by callumrollo** [comment]
Resolved in #24
