### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by QuLogic** [callumrollo/cmcrameri#37]
The `pyproject.toml` (and thus PyPI entry) lists https://callumrollo.github.io/cmcrameri as a documentation link. However, that link generates a 404 page.

**Comment by callumrollo** [comment]
oof! How embarrassing. Thanks for the catch! Fixed in #38

**Comment by Zerosimi** [comment]
Just FYI: The link is dead again, so 404 error.

**Comment by callumrollo** [comment]
Thanks for the bump @Zerosimi. This was fixed in #38 but wasn't pushed through to PyPI as there hadn't been a release since. I just published v1.9 and that has pushed through the docs fix to PyPI
