### ISSUE TITLE
Add scientific color map version number

### ISSUE THREAD

**Issue by MarkWieczorek** [callumrollo/cmcrameri#4]
The is a great project! I'm glad that someone finally put this on pip and conda.

I just have two small suggestions:

First, I think that it would be helpful if you could add the version of the Scientific Color Maps that you are using. These get updated from time to time, so it would be good to know what version is being used in `cmcrameri`. What if you added something like this to the init file? `__scm_version = 7.0` or `__version_scm = 7.0`

Second, as long as you are adding versions, it would be helpful to also define `__version`. Perhaps the easiest way to do this is with the [versioneer](https://github.com/python-versioneer/python-versioneer) project, which takes the version from the tag.

**Comment by callumrollo** [comment]
Hi Mark,

Thanks for the suggestion! This is my first package so it's good to get feedback on stuff I've missed. I'm working on a new release for the 7.0 colormaps toady. I'll add the version strings to the init file now and look into versioneer.
