### ISSUE TITLE
BatlowS categorical colormap

### ISSUE THREAD

**Issue by brosaplanella** [callumrollo/cmcrameri#7]
I would like to define the matplotlib cycler to use BatlowS but I haven't managed to get it working as I can't access the list of colors for the cycle. Is there already a way of doing so? If not, what would be the best way to implement it?

**Comment by callumrollo** [comment]
Do you want the RGB values for the steps of the colourmap? If so, you can read them from the .txt files that corresponds to the colourmap. You could download them directly from the zenodo source for the package
https://zenodo.org/record/4491293

Alternatively, the text files ship with the package. You can get the list of paths with
```from cmcrameri import cm
cm.paths```
These are three column csvs of RGB

**Comment by brosaplanella** [comment]
Yes, I already implemented this workaround in my code, but was wondering if that would be something useful for the package (accessing the color list so you can override the colour cycle in matplotlib).

**Comment by callumrollo** [comment]
I'm happy to take a PR on this if you have an idea for implementation? Or would signposting to cm.paths be sufficient?

**Comment by brosaplanella** [comment]
I think that for the moment signposting to `cm.paths` would suffice. An alternative way would be to add a variable in the Class (if possible) with the list of colours so it can be called directly from Python, but I think this would need to be done for all the colormaps (for consistency) and not sure how that would work.

**Comment by callumrollo** [comment]
I've added a section pointing to `cm.paths` to the README in  fe33d60. I'll close this issue now, but if I refactor to a class based package in future I'll add the `get_cmap` functionality that the inbuilt colormaps have
